set -g mouse on
set -s set-clipboard on
set -g extended-keys on

set -g bell-action any
set -g visual-bell on
set -gw monitor-bell on
set -g window-status-bell-style "fg=colour235,bg=colour220,bold"
set -g window-status-format "#{?window_bell_flag,● ,}#I:#W#{?window_flags,#{window_flags}, }"
